spring:
  application:
    name: aggregator
  rabbitmq:
    host: localhost  # e.g., localhost
    port: 5672                 # Default RabbitMQ port
    username: guest    # Your RabbitMQ username
    password: guest    # Your RabbitMQ password
    #virtual-host: your_vhost # Optional: If you use a virtual host

  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/aggregator_chapo
    username: root
    password: mdymen_pass
    driverClassName: com.mysql.cj.jdbc.Driver # Or the appropriate MySQL driver class


application:
  aggregator:
    enabled: true
    group-size: 5
    sleep: 20
